#!/bin/sh /etc/rc.common
# procd service for the optional MudiModem speed-test scheduler. Off by
# default (see /etc/mudimodem/speedtest-schedule.json). Respawned on crash.

START=96
STOP=10
USE_PROCD=1
PROG=/usr/sbin/mudimodem-speedtestd

start_service() {
	procd_open_instance
	procd_set_param command /usr/bin/python3 "$PROG"
	procd_set_param respawn
	procd_set_param stderr 1
	procd_close_instance
}
